apiVersion: v1
kind: Service
metadata:
  name: debate
  namespace: eum-backend
  labels:
    app: debate
spec:
  selector:
    app: debate
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP 