apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: eum-backend
  labels:
    app: api-gateway
type: Opaque
data:
  db-user: admin 
  db-password: password1232qw 
  jwt-secret: fdsgvdschvbfdhjsvdsbzcvfdvifudifdhviuhfdiuvhifds 