apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: eum-backend
  labels:
    app: api-gateway
type: Opaque
data:
  db-user: admin # root
  db-password: password1232qw # 1234
  jwt-secret: ZmRzZ3Zkc2NodmJmZGhqc3Zkc2J6Y3ZmZHZpZnVkaWZkaHZpdWhmZGl1dmhpZmRz 