apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-gateway-secret
  namespace: eum-backend
  labels:
    app: api-gateway
stringData:
  db-username: admin 
  db-password: password1232qw 
  jwt-secret: fdsgvdschvbfdhjsvdsbzcvfdvifudifdhviuhfdiuvhifds 