apiVersion: v1
kind: ConfigMap
metadata:
  name: discussion-room-config
  namespace: eum-ai
data:
  APP_NAME: "discussion-room"
  PORT: "8000"
  EUREKA_URL: "http://discovery.eum-backend.svc.cluster.local:8761/eureka"
  EUREKA_IP: "http://discovery.eum-backend.svc.cluster.local:8761/eureka"
  EUREKA_APP_NAME: "discussion-room"
  EUREKA_HOST: "discussion-room.eum-ai.svc.cluster.local"
  EUREKA_PORT: "8000"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  LIGHTWEIGHT_LLM_PROVIDER: "groq"
  HIGH_PERFORMANCE_LLM_PROVIDER: "groq"
  LIGHTWEIGHT_OLLAMA_URL: "http://ollama-service:11434"
  LIGHTWEIGHT_OLLAMA_MODEL: "gemma3:1b"
  LIGHTWEIGHT_OLLAMA_TIMEOUT: "20"
  HIGH_PERFORMANCE_OLLAMA_URL: "http://ollama-service:11434"
  HIGH_PERFORMANCE_OLLAMA_MODEL: "gemma3:1b"
  HIGH_PERFORMANCE_OLLAMA_TIMEOUT: "60"
  LIGHTWEIGHT_OPENAI_MODEL: "gpt-3.5-turbo"
  LIGHTWEIGHT_OPENAI_TIMEOUT: "30"
  HIGH_PERFORMANCE_OPENAI_MODEL: "gpt-4-turbo"
  HIGH_PERFORMANCE_OPENAI_TIMEOUT: "60"
  GROQ_LIGHTWEIGHT_MODEL: "gemma2-9b-it"
  GROQ_HIGHPERFORMANCE_MODEL: "gemma2-9b-it"
  S3_REGION: "ap-northeast-2"
  S3_BUCKET_NAME: "eum-msa-bucket"
  PYTHONPATH: "${PYTHONPATH}:."


# discussion-room , information 되는 버전