apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discussion-room-pvc
  namespace: eum-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 