apiVersion: v1
kind: Service
metadata:
  name: discussion-room
  namespace: eum-ai
  labels:
    app: discussion-room
spec:
  selector:
    app: discussion-room
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 