apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: eum-backend
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server-container
          image: 879657431997.dkr.ecr.ap-northeast-2.amazonaws.com/eum-eureka-server:5cdc08e774bcccae02829e4f1314d7699ef5d263
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m" 