apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: eum-backend
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP 