apiVersion: v1
kind: Service
metadata:
  name: alarm
  namespace: eum-backend
  labels:
    app: alarm
spec:
  selector:
    app: alarm
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP 