{{- if .Values.sealedSecrets.enabled }}
{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Release.Name }}-{{ $service.name }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $.Release.Name }}-{{ $service.name }}
    chart: {{ include "eum-ai.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  encryptedData:
    {{- range $key, $value := $service.sealedSecrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ $service.name }}-secret
      namespace: {{ $.Values.global.namespace }}
    type: Opaque
{{- end }}
{{- end }}
{{- end }} 