{{- if .Values.sealedSecrets.enabled }}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $service.name }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $service.name }}
    chart: {{ include "eum-ai.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  encryptedData:
    {{- if $service.secrets }}
    {{- range $key, $value := $service.secrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  template:
    metadata:
      name: {{ $service.name }}-secret
      namespace: {{ $.Values.global.namespace }}
      labels:
        app: {{ $service.name }}
    type: Opaque
{{- end }}
{{- end }}
{{- end }}