{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.secrets (not $.Values.sealedSecrets.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $service.name }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $service.name }}
    chart: {{ include "eum-ai.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  {{- range $key, $value := $service.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }} 