apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: eum-ai
  labels:
    app: classifier
spec:
  selector:
    app: classifier
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 