apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: eum-backend
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: 879657431997.dkr.ecr.ap-northeast-2.amazonaws.com/eum-user:cc8561e2403daa4435c8823cb0b28f64cc2e123f
          ports:
            - containerPort: 8081
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: jwt-secret
            - name: JWT_ACCESS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: jwt-access-expiration
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: jwt-refresh-expiration
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db-password
            - name: EUREKA_IP
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: eureka-ip
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: kafka-url
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: google-id
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: google-secret
            - name: GOOGLE_URI
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: google-uri
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: redis-url
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: "USER"
            - name: TZ
              value: "Asia/Seoul"
            - name: SPRING_JACKSON_TIME-ZONE
              value: "Asia/Seoul"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m" 