apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: eum-backend
  labels:
    app: user
type: Opaque
stringData:
  jwt-secret: fdsgvdschvbfdhjsvdsbzcvfdvifudifdhviuhfdiuvhifds
  db-user: admin
  db-password: password1232qw
  google-id: 995716805012-apkft4gt234g0m9saorpl2h6pukskfrn.apps.googleusercontent.com
  google-secret: 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 