apiVersion: apps/v1
kind: Deployment
metadata:
  name: information
  namespace: eum-backend
  labels:
    app: information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: information
  template:
    metadata:
      labels:
        app: information
    spec:
      containers:
        - name: information-container
          image: 879657431997.dkr.ecr.ap-northeast-2.amazonaws.com/eum-information:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: db-password
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: kafka-url
            - name: TRANSLATION_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: translation-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: jwt-secret
            - name: JWT_ACCESS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: jwt-access-expiration
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: jwt-refresh-expiration
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: s3-access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: s3-secret-key
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: s3-region
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: s3-bucket-name
            - name: EUREKA_IP
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: eureka-ip
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m" 