apiVersion: apps/v1
kind: Deployment
metadata:
  name: information
  namespace: eum-backend
  labels:
    app: information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: information
  template:
    metadata:
      labels:
        app: information
    spec:
      containers:
        - name: information
          image: 879657431997.dkr.ecr.ap-northeast-2.amazonaws.com/eum-information:5c0f2526855d1f3b3bcfda56b44b9cb908c7bee7
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: DB_URL
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: KAFKA_URL
            - name: TRANSLATION_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: TRANSLATION_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: JWT_SECRET
            - name: JWT_ACCESS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: JWT_ACCESS_EXPIRATION
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: JWT_REFRESH_EXPIRATION
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: information-secret
                  key: S3_SECRET_KEY
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: S3_REGION
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: S3_BUCKET_NAME
            - name: EUREKA_IP
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: EUREKA_IP
            - name: AI_IP
              valueFrom:
                configMapKeyRef:
                  name: information-config
                  key: AI_IP
            - name: SPRING_APPLICATION_NAME
              value: "INFORMATION"
            - name: TZ
              value: "Asia/Seoul"
            - name: SPRING_JACKSON_TIME-ZONE
              value: "Asia/Seoul"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "information.eum-backend.svc.cluster.local"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "30"
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "90"
            - name: EUREKA_CLIENT_HEARTBEAT_INTERVAL_IN_SECONDS
              value: "30"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m" 