apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: information-secret
  namespace: eum-backend
  labels:
    app: information
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjMycXc=
  JWT_SECRET: ZmRzZ3Zkc2NodmJmZGhqc3Zkc2J6Y3ZmZHZpZnVkaWZkaHZpdWhmZGl1dmhpZmRz
  translation-key: ZDc2M2FkMTMtYTIzNi00OTVmLWFlMjQtYmJlMzA4ZWExYWY2OmZ4
  S3_ACCESS_KEY: QUtJQTRaVDVMR082V0ZDQk9FRVo=
  S3_SECRET_KEY: cG1YTVV1dm5ZMXZqVUViZXdvS2RDLzZSMzJOR3dyZDArZVJYQlNZeQ== 