apiVersion: v1
kind: Service
metadata:
  name: community
  namespace: eum-backend
  labels:
    app: community
spec:
  selector:
    app: community
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP 