apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agentic-secret
  namespace: eum-ai
  labels:
    app: agentic
stringData:
  OPENAI_API_KEY: "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"
  LIGHTWEIGHT_OPENAI_API_KEY: "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"
  HIGH_PERFORMANCE_OPENAI_API_KEY: "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"
  GROQ_API_KEY: "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"
  S3_ACCESS_KEY: "AKIA4ZT5LGO6WFCBOEEZ"
  S3_SECRET_KEY: "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"
  GOOGLE_SERACH_API_KEY: "AIzaSyDr1tpp8ZwsvHywVNsZd0MkAyLWm2wBbJw"
  GOOGLE_SEARCH_ENGINE_ID: "f66960a81dd9d4f49"