apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-pvc
  namespace: eum-ai
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Sync=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2 
