apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-pvc
  namespace: eum-ai
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc 
