apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-pvc
  namespace: eum-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2 