apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: eum-ai
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 